-- Deprecated.
--
-- Webhook triggers are now versioned in migration
-- `supabase/migrations/20260710112000_portal_webhooks_vault.sql`.
--
-- Why this file is no longer executable:
-- 1) Inline headers in `supabase_functions.http_request` expose secrets in
--    trigger metadata.
-- 2) The old `input_requested` trigger fired on any UPDATE where status stayed
--    `open`, causing duplicate mails.
--
-- Current model:
-- - Trigger functions in `portal` dispatch via `pg_net`.
-- - Secret is read at runtime from Supabase Vault (`n8n_webhook_secret`).
-- - Transition guards are enforced in SQL and n8n workflow logic.
--
-- Secret bootstrap (manual, do not commit real values):
--   select vault.create_secret('<ROTATED_SECRET>', 'n8n_webhook_secret', 'RAIS portal webhook secret');
--
-- To inspect active triggers:
--   select event_object_table, trigger_name, event_manipulation, action_statement
--   from information_schema.triggers
--   where trigger_schema = 'portal'
--   order by event_object_table, trigger_name;


